import re
from datetime import datetime


def md_to_html(text: str) -> str:
    text = re.sub(r"^### (.+)$", r"<h3>\1</h3>", text, flags=re.MULTILINE)
    text = re.sub(r"^## (.+)$", r"<h2>\1</h2>", text, flags=re.MULTILINE)
    text = re.sub(r"^# (.+)$", r"<h1>\1</h1>", text, flags=re.MULTILINE)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    text = re.sub(r"^\- (.+)$", r"<li>\1</li>", text, flags=re.MULTILINE)
    text = re.sub(r"((?:<li>.*</li>\n?)+)", r"<ul>\1</ul>", text)
    text = re.sub(r"^\d+\.\s(.+)$", r"<li>\1</li>", text, flags=re.MULTILINE)
    paragraphs = []
    for block in text.split("\n\n"):
        block = block.strip()
        if not block:
            continue
        if block.startswith(("<h", "<ul", "<ol", "<li", "<table")):
            paragraphs.append(block)
        else:
            paragraphs.append(f"<p>{block}</p>")
    return "\n".join(paragraphs)


def generate_proposal_html(sections: dict, title: str = "Proposal Response") -> str:
    now = datetime.now().strftime("%B %d, %Y")

    toc_items = ""
    section_blocks = ""
    for i, (name, content) in enumerate(sections.items(), 1):
        anchor = name.lower().replace(" ", "-")
        toc_items += f'<li><a href="#{anchor}">{i}. {name}</a></li>\n'
        section_blocks += f"""
        <div class="section" id="{anchor}">
            <div class="section-number">Section {i}</div>
            <h2>{name}</h2>
            <div class="section-content">{md_to_html(content)}</div>
        </div>
        """

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #2c3e50; line-height: 1.7; background: #f8f9fa; }}
    .header {{ background: linear-gradient(135deg, #1a365d 0%, #2563eb 100%); color: white; padding: 60px 40px; text-align: center; }}
    .header h1 {{ font-size: 2.5em; margin-bottom: 10px; font-weight: 300; }}
    .header .date {{ font-size: 1.1em; opacity: 0.85; }}
    .download-bar {{ background: #1e293b; padding: 14px 40px; text-align: right; position: sticky; top: 0; z-index: 100; }}
    .download-bar button {{ background: #22c55e; color: white; border: none; padding: 10px 28px; font-size: 15px; border-radius: 6px; cursor: pointer; font-weight: 600; }}
    .download-bar button:hover {{ background: #16a34a; }}
    .container {{ max-width: 960px; margin: 0 auto; padding: 40px 20px; }}
    .toc {{ background: white; border-radius: 10px; padding: 30px 40px; margin-bottom: 30px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }}
    .toc h3 {{ color: #1a365d; margin-bottom: 15px; font-size: 1.3em; }}
    .toc ul {{ list-style: none; }}
    .toc li {{ padding: 6px 0; border-bottom: 1px solid #f1f5f9; }}
    .toc a {{ color: #2563eb; text-decoration: none; font-weight: 500; }}
    .toc a:hover {{ text-decoration: underline; }}
    .section {{ background: white; border-radius: 10px; padding: 35px 40px; margin-bottom: 24px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }}
    .section-number {{ font-size: 0.8em; text-transform: uppercase; letter-spacing: 2px; color: #2563eb; font-weight: 700; margin-bottom: 4px; }}
    .section h2 {{ color: #1a365d; font-size: 1.6em; margin-bottom: 20px; padding-bottom: 12px; border-bottom: 2px solid #e2e8f0; }}
    .section-content p {{ margin-bottom: 14px; }}
    .section-content h3 {{ color: #334155; margin: 20px 0 10px; }}
    .section-content ul {{ margin: 10px 0 14px 25px; }}
    .section-content li {{ margin-bottom: 6px; }}
    .section-content strong {{ color: #1e293b; }}
    .footer {{ text-align: center; padding: 40px; color: #94a3b8; font-size: 0.9em; }}
    @media print {{ .download-bar {{ display: none; }} body {{ background: white; }} .section {{ box-shadow: none; border: 1px solid #e2e8f0; }} }}
</style>
</head>
<body>

<div class="header">
    <h1>{title}</h1>
    <div class="date">Generated on {now}</div>
</div>

<div class="download-bar">
    <button onclick="downloadHTML()">Download as HTML</button>
</div>

<div class="container">
    <div class="toc">
        <h3>Table of Contents</h3>
        <ul>{toc_items}</ul>
    </div>
    {section_blocks}
</div>

<div class="footer">
    Generated by RFP Agent Suite
</div>

<script>
function downloadHTML() {{
    var clone = document.documentElement.cloneNode(true);
    var bar = clone.querySelector('.download-bar');
    if (bar) bar.remove();
    var html = '<!DOCTYPE html>' + clone.outerHTML;
    var blob = new Blob([html], {{type: 'text/html'}});
    var a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = '{title.replace(" ", "_")}.html';
    a.click();
    URL.revokeObjectURL(a.href);
}}
</script>

</body>
</html>"""
